### ISSUE TITLE
self.base_strategy has no attribute 'rgb_inputs'

### ISSUE THREAD

**Issue by WangMengxiao319** [MeteorsHub/RelayLearning#1]
Hi, thanks for your valuable work. 

When I try to do the simple test as instruction[https://github.com/MeteorsHub/RelayLearning?tab=readme-ov-file#simple-test](url), something went wrong in **self.base_strategy**, I found it is NoneType. I did not change anything in **_config/relay_test.yaml_** except for the _root_path_. The error is as follows:
```
Traceback (most recent call last):
  File "/home/lzy/mancy/RelayLearning/predict_test.py", line 223, in <module>
    predict_test()
  File "/home/lzy/mancy/RelayLearning/predict_test.py", line 82, in predict_test
    model = get_model(task_conf['model']['name'], **task_conf['model']['kwargs'])
  File "/home/lzy/mancy/RelayLearning/models/__init__.py", line 34, in get_model
    return all_models[name](**kwargs)
  File "/home/lzy/mancy/RelayLearning/models/doublegan.py", line 88, in __init__
    self.replay_post_aug_pipe = get_data_aug_pipe(rgb=self.base_strategy.rgb_inputs) if replay_post_aug else None
AttributeError: 'NoneType' object has no attribute 'rgb_inputs'
```

**Comment by MeteorsHub** [comment]
It could be a bug about using before defining. I change the `rgb=self.base_strategy.rgb_inputs` to `rgb=True` directly. It should solve the problem.
